### ISSUE TITLE
Bug: Incorrect guideline for npx and yarn installation

### ISSUE THREAD

**Issue by kevinsslin** [ephemeraHQ/message-kit#103]
### Describe the bug

The current installation instructions in the documentation incorrectly suggest using `npm dev` to start the development server.
![image](https://github.com/user-attachments/assets/bd97254d-d57f-49d0-b1e3-8e734d594553)

### Expected behavior

Running the command should start the development server as expected. The server should successfully compile the project, enter watch mode, and display any necessary output or logs in the terminal without errors.

### Steps to reproduce the bug

1. Run npm dev as per the guideline.
2. Observe the error message:
![image](https://github.com/user-attachments/assets/0a78168f-0286-4ed5-8d0b-be6ca98ab29c)

**Comment by fabriguespe** [comment]
Thanks! Fixed in the upcoing PR. 

Will merge soon

**Comment by kevinsslin** [comment]
I’ve also encountered some issues when trying to run yarn install, so it might need to be fixed.

**Comment by fabriguespe** [comment]
Hey can you try the latest version of the cli? Would also be helpfull if you can share yarn install errors?

Join us in converse! https://converse.xyz/group-invite/a0XKzl9oVpWNXcuYDZLMf

**Comment by fabriguespe** [comment]
@kevinsslin Merged !, can you try?

Message me at fabri.converse.xyz if you have problems

**Comment by kevinsslin** [comment]
![image](https://github.com/user-attachments/assets/88a59aa3-9529-4690-bf74-be7b18a9b47f)
I notice that the description in CLI part haven't been solved.

**Comment by kevinsslin** [comment]
![image](https://github.com/user-attachments/assets/e6ea794e-0cdd-4844-b826-a6d9a61f8b0b)
![image](https://github.com/user-attachments/assets/4af73587-b211-4d46-a3c5-1dcb0536d0e3)

For the yarn installation part, we should update the command `yarn i` to `yarn` or `yarn install`.

**Comment by kevinsslin** [comment]
![image](https://github.com/user-attachments/assets/d8e4bef7-e512-49c3-af76-e3e404fc44ce)
While running the `yarn install` command, I encountered multiple warnings related to missing dependencies and experimental features. The dependencies such as ws@8.1.0, y18n@5.0.8, and others could not be found in the cache and had to be fetched from the remote registry.

`5:46:02 AM - Starting compilation in watch mode...
[1]
[1] src/commands.ts(1,35): error TS2307: Cannot find module '@xmtp/message-kit' or its corresponding type declarations.
[1] src/handler/agent.ts(1,38): error TS2307: Cannot find module '@xmtp/message-kit' or its corresponding type declarations.
[1] src/handler/agent.ts(5,8): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[1] src/handler/agent.ts(6,5): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
[1] src/handler/agent.ts(19,5): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
[1] src/handler/agent.ts(22,5): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
[1] src/handler/agent.ts(25,5): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
[1] src/handler/game.ts(1,32): error TS2307: Cannot find module '@xmtp/message-kit' or its corresponding type declarations.
[1] src/handler/loyalty.ts(1,38): error TS2307: Cannot find module '@xmtp/message-kit' or its corresponding type declarations.
[1] src/handler/loyalty.ts(17,3): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
[1] src/handler/loyalty.ts(28,12): error TS7006: Parameter 'entry' implicitly has an 'any' type.
[1] src/handler/loyalty.ts(28,19): error TS7006: Parameter 'index' implicitly has an 'any' type.
[1] src/handler/splitpayment.ts(1,32): error TS2307: Cannot find module '@xmtp/message-kit' or its corresponding type declarations.
[1] src/handler/splitpayment.ts(5,8): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[1] src/handler/splitpayment.ts(6,5): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
[1] src/handler/splitpayment.ts(34,72): error TS7006: Parameter 'member' implicitly has an 'any' type.
[1] src/handler/tipping.ts(1,38): error TS2307: Cannot find module '@xmtp/message-kit' or its corresponding type declarations.
[1] src/handler/tipping.ts(11,6): error TS7006: Parameter 'member' implicitly has an 'any' type.
[1] src/handler/transaction.ts(1,32): error TS2307: Cannot find module '@xmtp/message-kit' or its corresponding type declarations.
[1] src/handler/transaction.ts(75,25): error TS2304: Cannot find name 'URLSearchParams'.
[1] src/index.ts(1,37): error TS2307: Cannot find module '@xmtp/message-kit' or its corresponding type declarations.
[1] src/index.ts(38,3): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
[1] src/index.ts(63,17): error TS7006: Parameter 'app' implicitly has an 'any' type.
[1] src/index.ts(64,13): error TS7006: Parameter 'command' implicitly has an 'any' type.
[1] src/lib/openai.ts(1,20): error TS2307: Cannot find module 'dotenv' or its corresponding type declarations.
[1] src/lib/openai.ts(2,26): error TS2307: Cannot find module 'express' or its corresponding type declarations.
[1] src/lib/openai.ts(5,20): error TS2307: Cannot find module 'openai' or its corresponding type declarations.
[1] src/lib/openai.ts(7,11): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[1] src/lib/openai.ts(40,5): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
[1] src/lib/openai.ts(47,23): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[1] src/lib/openai.ts(77,5): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
[1] src/lib/stack.ts(1,29): error TS2307: Cannot find module '@stackso/js-core' or its corresponding type declarations.
[1] src/lib/stack.ts(6,8): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[1] src/lib/stack.ts(7,5): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
[1] src/lib/stack.ts(12,15): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
[1]
[1] 5:46:02 AM - Found 35 errors. Watching for file changes.
(node:11640) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11640) ExperimentalWarning: Use `importAttributes` instead of `importAssertions`
(Use `node --trace-warnings ...` to show where the warning was created)
[ NaN ]
/Users/kevinslin/Desktop/repos/xuedao/glhf/24-devcon/msg-kit/test-group-yarn/.yarn/unplugged/nodemon-npm-3.1.7-ef86478222/node_modules/nodemon/lib/version.js:17
  var promise = findPackage(path.dirname(module.parent.filename))
                                                       ^

TypeError: Cannot read properties of undefined (reading 'filename')
    at version (/Users/kevinslin/Desktop/repos/xuedao/glhf/24-devcon/msg-kit/test-group-yarn/.yarn/unplugged/nodemon-npm-3.1.7-ef86478222/node_modules/nodemon/lib/version.js:17:56)
    at pin (/Users/kevinslin/Desktop/repos/xuedao/glhf/24-devcon/msg-kit/test-group-yarn/.yarn/unplugged/nodemon-npm-3.1.7-ef86478222/node_modules/nodemon/lib/version.js:10:10)
    at /Users/kevinslin/Desktop/repos/xuedao/glhf/24-devcon/msg-kit/test-group-yarn/.yarn/unplugged/nodemon-npm-3.1.7-ef86478222/node_modules/nodemon/lib/config/index.js:81:5
    at normaliseRules (/Users/kevinslin/Desktop/repos/xuedao/glhf/24-devcon/msg-kit/test-group-yarn/.yarn/unplugged/nodemon-npm-3.1.7-ef86478222/node_modules/nodemon/lib/config/load.js:125:3)
    at ready (/Users/kevinslin/Desktop/repos/xuedao/glhf/24-devcon/msg-kit/test-group-yarn/.yarn/unplugged/nodemon-npm-3.1.7-ef86478222/node_modules/nodemon/lib/config/load.js:108:9)
    at /Users/kevinslin/Desktop/repos/xuedao/glhf/24-devcon/msg-kit/test-group-yarn/.yarn/unplugged/nodemon-npm-3.1.7-ef86478222/node_modules/nodemon/lib/config/load.js:111:7
    at callback (/Users/kevinslin/Desktop/repos/xuedao/glhf/24-devcon/msg-kit/test-group-yarn/.yarn/unplugged/nodemon-npm-3.1.7-ef86478222/node_modules/nodemon/lib/config/load.js:143:5)
    at /Users/kevinslin/Desktop/repos/xuedao/glhf/24-devcon/msg-kit/test-group-yarn/.yarn/unplugged/nodemon-npm-3.1.7-ef86478222/node_modules/nodemon/lib/config/load.js:196:5
    at callback (/Users/kevinslin/Desktop/repos/xuedao/glhf/24-devcon/msg-kit/test-group-yarn/.yarn/unplugged/nodemon-npm-3.1.7-ef86478222/node_modules/nodemon/lib/config/load.js:143:5)
    at /Users/kevinslin/Desktop/repos/xuedao/glhf/24-devcon/msg-kit/test-group-yarn/.yarn/unplugged/nodemon-npm-3.1.7-ef86478222/node_modules/nodemon/lib/config/load.js:183:5

Node.js v21.7.1
^CJob [1], 'tsc -w' has ended`

While trying to run yarn dev, I encountered numerous TypeScript errors, along with missing type declarations for several modules, including @xmtp/message-kit, process, console, and more.

**Comment by fabriguespe** [comment]
Nice now the CLI messages dont have package manager and the readmes were improved
https://github.com/ephemeraHQ/message-kit/pull/106

Already published in v15 of CLI

**Comment by fabriguespe** [comment]
> ![image](https://private-user-images.githubusercontent.com/86810837/379475159-d8e4bef7-e512-49c3-af76-e3e404fc44ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MjIzNjksIm5iZiI6MTcyOTcyMjA2OSwicGF0aCI6Ii84NjgxMDgzNy8zNzk0NzUxNTktZDhlNGJlZjctZTUxMi00OWMzLWFmNzYtZTNlNDA0ZmM0NGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDIyMjEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMWNmZGQzODk3ZTM3MzdjN2IwNWQ3NzY0YTcxN2JhM2JlMTg1NGRmYmY4MDFkZmI3YTlmNDQ4YTc0YjExMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YNO0m7bdng4vAs6fYDmNwwESiNmX-qO7WD8COOPducQ) While running the `yarn install` command, I encountered multiple warnings related to missing dependencies and experimental features. The dependencies such as ws@8.1.0, y18n@5.0.8, and others could not be found in the cache and had to be fetched from the remote registry.
> 
> ```
> src/commands.ts(1,35): error TS2307: Cannot find module '@xmtp/message-kit' or its corresponding type declarations.
> src/handler/agent.ts(1,38): error TS2307: Cannot find module '@xmtp/message-kit' or its corresponding type declarations.
> src/handler/agent.ts(5,8): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
> src/handler/agent.ts(6,5): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
> ...
> (Additional errors with `nodemon`):
> TypeError: Cannot read properties of undefined (reading 'filename') in nodemon/lib/version.js:17
> Node.js v21.7.1
> ```
> 
> While trying to run `yarn dev`, I encountered numerous TypeScript errors, along with missing type declarations for several modules, including @xmtp/message-kit, process, console, and more. You can check the details here: https://app.warp.dev/block/pB0pHPhexIaqoIl45dh7VK

Can you start a new issue here? Seems you need to install typescript.

**Comment by kevinsslin** [comment]
I have opened a new issue to track this problem: https://github.com/ephemeraHQ/message-kit/issues/107

**Comment by kevinsslin** [comment]
> > ![image](https://private-user-images.githubusercontent.com/86810837/379475159-d8e4bef7-e512-49c3-af76-e3e404fc44ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MjIzNjksIm5iZiI6MTcyOTcyMjA2OSwicGF0aCI6Ii84NjgxMDgzNy8zNzk0NzUxNTktZDhlNGJlZjctZTUxMi00OWMzLWFmNzYtZTNlNDA0ZmM0NGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDIyMjEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMWNmZGQzODk3ZTM3MzdjN2IwNWQ3NzY0YTcxN2JhM2JlMTg1NGRmYmY4MDFkZmI3YTlmNDQ4YTc0YjExMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YNO0m7bdng4vAs6fYDmNwwESiNmX-qO7WD8COOPducQ) While running the `yarn install` command, I encountered multiple warnings related to missing dependencies and experimental features. The dependencies such as ws@8.1.0, y18n@5.0.8, and others could not be found in the cache and had to be fetched from the remote registry.
> > ```
> > src/commands.ts(1,35): error TS2307: Cannot find module '@xmtp/message-kit' or its corresponding type declarations.
> > src/handler/agent.ts(1,38): error TS2307: Cannot find module '@xmtp/message-kit' or its corresponding type declarations.
> > src/handler/agent.ts(5,8): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
> > src/handler/agent.ts(6,5): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
> > ...
> > (Additional errors with `nodemon`):
> > TypeError: Cannot read properties of undefined (reading 'filename') in nodemon/lib/version.js:17
> > Node.js v21.7.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > While trying to run `yarn dev`, I encountered numerous TypeScript errors, along with missing type declarations for several modules, including @xmtp/message-kit, process, console, and more. You can check the details here: https://app.warp.dev/block/pB0pHPhexIaqoIl45dh7VK
> 
> * Can you start a new issue here? Seems you need to install typescript.
> * About the warnings they already come with XMTP packages. They are normal

I have opened a new issue to track this problem: https://github.com/ephemeraHQ/message-kit/issues/107
