### ISSUE TITLE
Bug: Issues with yarn 4.5.1

### ISSUE THREAD

**Issue by humanagent** [ephemeraHQ/message-kit#124]
### Describe the bug

after installing with CLI with yarn 4.5.1. The rest work

`yarn create message-kit`

```
Restarting 'dist/index.js'

node:internal/modules/run_main:122
    triggerUncaughtException(
    ^
Error: @xmtp/message-kit tried to access @xmtp/node-bindings, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @xmtp/node-bindings (via "@xmtp/node-bindings/package.json")
Required by: @xmtp/message-kit@npm:1.1.7-beta.21 (via /Users/fabrizioguespe/.yarn/berry/cache/@xmtp-message-kit-npm-1.1.7-beta.21-9084d4b363-10c0.zip/node_modules/@xmtp/message-kit/dist/index.js)

    at makeError (/Users/fabrizioguespe/fa4/.pnp.cjs:9143:34)
    at resolveToUnqualified (/Users/fabrizioguespe/fa4/.pnp.cjs:10781:21)
    at Object.resolveToUnqualified (/Users/fabrizioguespe/fa4/.pnp.cjs:10961:26)
    at resolve$1 (file:///Users/fabrizioguespe/fa4/.pnp.loader.mjs:2031:31)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:240:30)
    at handleMessage (node:internal/modules/esm/worker:199:24)
    at checkForMessages (node:internal/modules/esm/worker:141:28)
    at process.<anonymous> (node:internal/modules/esm/worker:160:5)
    at process.emit (node:events:518:28)

Node.js v22.11.0
Failed running 'dist/index.js'
```

Workaround:
- Use yarn 1

**Comment by humanagent** [comment]
added
`nodeLinker: node-modules`
