### ISSUE TITLE
Bug: running gm template locally

### ISSUE THREAD

**Issue by omariosman** [ephemeraHQ/message-kit#127]
### Describe the bug

I am trying to run a gm template, however, after I run these commands, I came across the following errors

### **Environment**
Ubuntu 22.04.3 LTS
I tried node v20.18.0 and node 18.17.0 
I tried yarn version 3.4.1 and yarn 1.22.22 but both failed

### **Commands:**
```
git clone https://github.com/ephemeraHQ/message-kit
cd templates/gm
yarn install
yarn dev
```

### **Errors:**
```
Restarting 'dist/index.js'
/home/kareemikassab/ETH-Global/mytest/node_modules/@xmtp/node-bindings/dist/index.js:359
    throw new Error('Failed to load native binding', { cause: loadErrors })
          ^
 
Error: Failed to load native binding
    at Object.<anonymous> (/home/kareemikassab/ETH-Global/mytest/node_modules/@xmtp/node-bindings/dist/index.js:359:11)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at cjsLoader (node:internal/modules/esm/translators:346:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  [cause]: [
    Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/kareemikassab/ETH-Global/mytest/node_modules/@xmtp/node-bindings/dist/bindings_node.linux-x64-gnu.node)
        at Module._extensions..node (node:internal/modules/cjs/loader:1586:18)
        at Module.load (node:internal/modules/cjs/loader:1288:32)
        at Module._load (node:internal/modules/cjs/loader:1104:12)
        at Module.require (node:internal/modules/cjs/loader:1311:19)
        at require (node:internal/modules/helpers:179:18)
        at requireNative (/home/kareemikassab/ETH-Global/mytest/node_modules/@xmtp/node-bindings/dist/index.js:211:16)
        at Object.<anonymous> (/home/kareemikassab/ETH-Global/mytest/node_modules/@xmtp/node-bindings/dist/index.js:332:17)
        at Module._compile (node:internal/modules/cjs/loader:1469:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
        at Module.load (node:internal/modules/cjs/loader:1288:32) {
      code: 'ERR_DLOPEN_FAILED'
    },
    Error: Cannot find module '@xmtp/node-bindings-linux-x64-gnu'
    Require stack:
    - /home/kareemikassab/ETH-Global/mytest/node_modules/@xmtp/node-bindings/dist/index.js
        at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
        at Module._load (node:internal/modules/cjs/loader:1051:27)
        at Module.require (node:internal/modules/cjs/loader:1311:19)
        at require (node:internal/modules/helpers:179:18)
        at requireNative (/home/kareemikassab/ETH-Global/mytest/node_modules/@xmtp/node-bindings/dist/index.js:216:16)
        at Object.<anonymous> (/home/kareemikassab/ETH-Global/mytest/node_modules/@xmtp/node-bindings/dist/index.js:332:17)
        at Module._compile (node:internal/modules/cjs/loader:1469:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
        at Module.load (node:internal/modules/cjs/loader:1288:32)
        at Module._load (node:internal/modules/cjs/loader:1104:12) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/home/kareemikassab/ETH-Global/mytest/node_modules/@xmtp/node-bindings/dist/index.js'
      ]
    }
  ]
}
 
Node.js v20.18.0
Failed running 'dist/index.js'

```
### Expected behavior

A Gm template app is running locally properly

### Steps to reproduce the bug

Apply the same commands above using node v20.18.0 and Ubuntu 22.04.3 LTS

**Comment by fabriguespe** [comment]
Which yarn version? Can you try with v1?

We have an issue with yarn 4

**Comment by fabriguespe** [comment]
cc @rygine

**Comment by humanagent** [comment]
Can you try using the cli instead?

`yarn create message-kit`

**Comment by omariosman** [comment]
@humanagent  I used the cli as well but no luck, it gives the same result :'(

**Comment by humanagent** [comment]
can you ping me at https://converse.xyz/dm/fabri

**Comment by rygine** [comment]
@omariosman are you able to try with ubuntu 24.04? it should work in that environment.

**Comment by humanagent** [comment]
Fix same issue updating ubuntu https://github.com/ephemeraHQ/message-kit/issues/114

Let me know!
